# -*- coding: utf-8 -*-
"""Webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJWgeUYZML1jWOdGiamJBJAtN1YSIBSH
"""

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
import requests
import matplotlib.pyplot as plt

url = 'https://www.amazon.in/gp/bestsellers/books'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9',
    'Accept-Encoding': 'gzip, deflate, br',
    'Referer': 'https://www.amazon.in',
    'Connection': 'keep-alive'
}

page = requests.get(url, headers=headers)
page

soup = bs(page.content, 'html.parser')

Books = soup.find_all('div',class_='_cDEzb_p13n-sc-css-line-clamp-1_1Fn1y')

name_of_books = []
author=[]

for i in range(len(Books)):
  if i%2==0:
    name_of_books.append(Books[i].text.strip())
  else:
      author.append(Books[i].text.strip())

print("Name_of_Books ",name_of_books)
print("Authors: ",author)

len(name_of_books)

len(author)

# Scrape prices correctly
Book_Price = soup.find_all('span', class_='_cDEzb_p13n-sc-price_3mJ9Z')
Price = []

for price in Book_Price:
    Price.append(price.text.strip())

print("Prices:", Price)
len(Price)

ratings = soup.find_all('a', class_='a-link-normal', title=True)
customer_ratings = []
for a in ratings:
    if 'out of 5 stars' in a['title']:
        customer_ratings.append(a['title'])

print("Customer Ratings:",customer_ratings)
len(customer_ratings)

Price = Price[:29]
customer_ratings=customer_ratings[:29]
name_of_books = name_of_books[:29]
author=author[:29]

data = {
        'name_of_books' : name_of_books,
        'author' : author,
        'customer_ratings' : customer_ratings,
        'Price' : Price
}

df=pd.DataFrame(data)
df

#Cleaning and preprocessing

#Clean customer ratings
df['customer_ratings'] = df['customer_ratings'].astype(str).str.split(' ').str[0].astype(float)

# Clean the price
df['Price'] = df['Price'].astype(str).replace({'₹': '', ',': ''}, regex=True).astype(float)

df

# Summary Statistics
average_rating = df['customer_ratings'].mean()
average_price = df['Price'].mean()

# Price vs Rating Scatter Plot
plt.scatter(df['Price'], df['customer_ratings'])
plt.title('Price vs Customer Ratings')
plt.xlabel('Price (in ₹)')
plt.ylabel('Customer Ratings')
plt.show()

# Output results
print(f"Average Rating: {average_rating}")
print(f"Average Price: {average_price}")

df.to_csv("Amazon's most selling Books.csv",index=False)